//
//  GeneratedPluginRegistrant.swift
//  Runner
//
//  This file is auto-generated by Flutter — do not edit manually.
//  Run: flutter pub get
//

import Flutter
import UIKit

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  // Plugins are registered automatically by flutter pub get
}
